# Import thư viện sử dụng

Sử dụng 3 model:
 - lightgmb
 - catboost
 - xgboost

In [1]:
!pip install lightgbm xgboost catboost

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: lightgbm in /Users/nals_macbook_108/Library/Python/3.9/lib/python/site-packages (4.6.0)
Requirement already satisfied: xgboost in /Users/nals_macbook_108/Library/Python/3.9/lib/python/site-packages (2.1.4)
Requirement already satisfied: catboost in /Users/nals_macbook_108/Library/Python/3.9/lib/python/site-packages (1.2.10)
Requirement already satisfied: numpy>=1.17.0 in /Users/nals_macbook_108/Library/Python/3.9/lib/python/site-packages (from lightgbm) (1.26.4)
Requirement already satisfied: scipy in /Users/nals_macbook_108/Library/Python/3.9/lib/python/site-packages (from lightgbm) (1.13.1)
Requirement already satisfied: graphviz in /Users/nals_macbook_108/Library/Python/3.9/lib/python/site-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /Users/nals_macbook_108/Library/Python/3.9/lib/python/site-packages (from catboost) (3.9.3)
Requirement already satisfied: pandas<4.0,>=0.24 in /Users/nals_macbook_108/Library/Python/3.9/lib/python/site-packages (from catboost) (2.2.3)
Requirement already satisfied: plotly in /Users/nals_macbook_108/Library/Python/3.9/lib/python/site-packages (from catboost) (6.7.0)
Requirement already satisfied: six in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from catboost) (1.15.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/nals_macbook_108/Library/Python/3.9/lib/python/site-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/nals_macbook_108/Library/Python/3.9/lib/python/site-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/nals_macbook_108/Library/Python/3.9/lib/python/site-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in /Users/nals_macbook_108/Library/Python/3.9/lib/python/site-packages (from matplotlib->catboost) (1.3.0)
Requirement already satisfied: cycler>=0.10 in /Users/nals_macbook_108/Library/Python/3.9/lib/python/site-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Users/nals_macbook_108/Library/Python/3.9/lib/python/site-packages (from matplotlib->catboost) (4.59.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/nals_macbook_108/Library/Python/3.9/lib/python/site-packages (from matplotlib->catboost) (1.4.7)
Requirement already satisfied: packaging>=20.0 in /Users/nals_macbook_108/Library/Python/3.9/lib/python/site-packages (from matplotlib->catboost) (25.0)
Requirement already satisfied: pillow>=8 in /Users/nals_macbook_108/Library/Python/3.9/lib/python/site-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /Users/nals_macbook_108/Library/Python/3.9/lib/python/site-packages (from matplotlib->catboost) (3.2.3)
Requirement already satisfied: importlib-resources>=3.2.0 in /Users/nals_macbook_108/Library/Python/3.9/lib/python/site-packages (from matplotlib->catboost) (6.5.2)
Requirement already satisfied: zipp>=3.1.0 in /Users/nals_macbook_108/Library/Python/3.9/lib/python/site-packages (from importlib-resources>=3.2.0->matplotlib->catboost) (3.21.0)
Requirement already satisfied: narwhals>=1.15.1 in /Users/nals_macbook_108/Library/Python/3.9/lib/python/site-packages (from plotly->catboost) (2.13.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: /Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import r2_score
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import HistGradientBoostingRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.pipeline import Pipeline
from sklearn.svm import SVR
from sklearn.preprocessing import MinMaxScaler, PolynomialFeatures, StandardScaler, Normalizer, LabelEncoder, OneHotEncoder
from catboost import CatBoostRegressor
from lightgbm import LGBMRegressor
import xgboost as xgb

# 1. Đọc dữ liệu

In [3]:

df = pd.read_csv('../data/preproces_data.csv')
df.head()

,Diện tích đất:,Hướng cửa chính:,Giấy tờ pháp lý:,Đặc điểm nhà/đất:,Loại hình đất:,Chiều ngang:,Chiều dài:,Số phòng ngủ:,Số phòng vệ sinh:,Loại hình nhà ở:,...,Tầng số:,Hướng ban công:,Đặc điểm căn hộ:,Loại hình văn phòng:,district,city,Phân khu/Lô/Block/Tháp,has_floor_number,Price (trieu VND),log_price
0,170.0,Tây Bắc,Đã có sổ,Mặt tiền,Đất thổ cư,13.0,13.00,2.0,2.0,"Nhà mặt phố, mặt tiền",...,26.0,Đông Bắc,Căn góc,Shophouse,thành phố tân an,long an,Không thuộc project/block,1,419.0,6.040255
1,64.2,Tây Bắc,Đã có sổ,Nở hậu,Đất thổ cư,4.0,16.05,2.0,2.0,"Nhà mặt phố, mặt tiền",...,26.0,Đông Bắc,Căn góc,Shophouse,quận 9,tp hồ chí minh,Không thuộc project/block,1,936.0,6.842683
2,108.0,Tây,Đã có sổ,Nở hậu,Đất thổ cư,5.0,20.00,6.0,6.0,"Nhà ngõ, hẻm",...,26.0,Đông Bắc,Căn góc,Shophouse,quận 7,tp hồ chí minh,Không thuộc project/block,1,9500.0,9.159152
3,42.0,Nam,Đã có sổ,Nở hậu,Đất thổ cư,4.0,11.00,5.0,3.0,"Nhà ngõ, hẻm",...,26.0,Đông Bắc,Căn góc,Shophouse,quận 11,tp hồ chí minh,Không thuộc project/block,1,6500.0,8.779711
4,93.0,Nam,Đã có sổ,Hẻm xe hơi,Đất thổ cư,5.5,17.00,5.0,6.0,"Nhà ngõ, hẻm",...,26.0,Đông Bắc,Căn góc,Shophouse,quận bình tân,tp hồ chí minh,Không thuộc project/block,1,5000.0,8.517393

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5947 entries, 0 to 5946
Data columns (total 26 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Diện tích đất:            5947 non-null   float64
 1   Hướng cửa chính:          5947 non-null   object
 2   Giấy tờ pháp lý:          5947 non-null   object
 3   Đặc điểm nhà/đất:         5947 non-null   object
 4   Loại hình đất:            5947 non-null   object
 5   Chiều ngang:              5947 non-null   float64
 6   Chiều dài:                5947 non-null   float64
 7   Số phòng ngủ:             5947 non-null   float64
 8   Số phòng vệ sinh:         5947 non-null   float64
 9   Loại hình nhà ở:          5947 non-null   object
 10  Tình trạng nội thất:      5947 non-null   object
 11  Diện tích sử dụng:        5947 non-null   float64
 12  Tình trạng bất động sản:  5947 non-null   object
 13  Diện tích:                5947 non-null   float64
 14  Loại hình căn hộ:         5947 non-null   object
 15  Tổng số tầng:             5947 non-null   float64
 16  Tầng số:                  5947 non-null   float64
 17  Hướng ban công:           5947 non-null   object
 18  Đặc điểm căn hộ:          5947 non-null   object
 19  Loại hình văn phòng:      5947 non-null   object
 20  district                  5947 non-null   object
 21  city                      5947 non-null   object
 22  Phân khu/Lô/Block/Tháp    5947 non-null   object
 23  has_floor_number          5947 non-null   int64
 24  Price (trieu VND)         5947 non-null   float64
 25  log_price                 5947 non-null   float64
dtypes: float64(11), int64(1), object(14)
memory usage: 1.2+ MB

# 1. One-hot endcoding với các

In [5]:
object_cols = df.loc[:, df.dtypes == object].columns # tìm các cột kiểu dữ liệu object trong dataframe

In [6]:
df_temp = df.copy()
onehot_dict = {}

for col in object_cols:
    enc = OneHotEncoder(sparse_output=False)  # bỏ luôn .toarray()
    transformed = enc.fit_transform(df_temp[col].values.reshape(-1, 1))
    onehot_dict[col] = enc
    
    # Đặt tên cột theo tên cột gốc để tránh trùng
    feature_names = [f"{col}_{cat}" for cat in enc.categories_[0]]
    ohe_df = pd.DataFrame(transformed, columns=feature_names, index=df_temp.index)
    
    df_temp = df_temp.drop([col], axis=1)
    df_temp = df_temp.join(ohe_df)

In [7]:
df_temp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5947 entries, 0 to 5946
Columns: 429 entries, Diện tích đất: to Phân khu/Lô/Block/Tháp_W3
dtypes: float64(428), int64(1)
memory usage: 19.5 MB

In [8]:
print("Số cột sau One-Hot:", df_temp.shape[1])

Số cột sau One-Hot: 429

Sau khi One-Hot Endcoding, tổng quan kết quả:
1) 429 columns: từ 29 columns ban đầu đã chuyển đổi thành 429 cột vì mỗi giá tị unique của cột chữ thành 1 cột riêng
2) 5947 mẫu dữ liệu (đáp ứng yêu cầu - tối thiểu 5000)
3) dtype gồm 2 loại: 
- float64 - 428 columns
- int64 - 1 columns

Tuy nhiên hiện tại các name column không phải ở dạng unidecode, nên XGBoost không xử lý được, cần chuyển về unidecode để phục vụ việc train data

In [9]:
from unidecode import unidecode
import re

def clean_col(col):
    col = unidecode(col)
    col = re.sub(r'[^A-Za-z0-9_]', '_', col)
    return col

df_temp.columns = [clean_col(col) for col in df_temp.columns]

print("Tên cột sau clean:", df_temp.columns.tolist()[:429])

Tên cột sau clean: ['Dien_tich_dat_', 'Chieu_ngang_', 'Chieu_dai_', 'So_phong_ngu_', 'So_phong_ve_sinh_', 'Dien_tich_su_dung_', 'Dien_tich_', 'Tong_so_tang_', 'Tang_so_', 'has_floor_number', 'Price__trieu_VND_', 'log_price', 'Huong_cua_chinh__Bac', 'Huong_cua_chinh__Nam', 'Huong_cua_chinh__Tay', 'Huong_cua_chinh__Tay_Bac', 'Huong_cua_chinh__Tay_Nam', 'Huong_cua_chinh__Dong', 'Huong_cua_chinh__Dong_Bac', 'Huong_cua_chinh__Dong_Nam', 'Giay_to_phap_ly__Giay_to_khac', 'Giay_to_phap_ly__Dang_cho_so', 'Giay_to_phap_ly__Da_co_so', 'Dac_diem_nha_dat__Hem_xe_hoi', 'Dac_diem_nha_dat__Mat_tien', 'Dac_diem_nha_dat__No_hau', 'Loai_hinh_dat__Dat_cong_nghiep', 'Loai_hinh_dat__Dat_nong_nghiep', 'Loai_hinh_dat__Dat_nen_du_an', 'Loai_hinh_dat__Dat_tho_cu', 'Loai_hinh_nha_o__Nha_biet_thu', 'Loai_hinh_nha_o__Nha_mat_pho__mat_tien', 'Loai_hinh_nha_o__Nha_ngo__hem', 'Loai_hinh_nha_o__Nha_pho_lien_ke', 'Tinh_trang_noi_that__Ban_giao_tho', 'Tinh_trang_noi_that__Hoan_thien_co_ban', 'Tinh_trang_noi_that__Noi_that_cao_cap', 'Tinh_trang_noi_that__Noi_that_day_du', 'Tinh_trang_bat_dong_san__Chua_ban_giao', 'Tinh_trang_bat_dong_san__Da_ban_giao', 'Loai_hinh_can_ho__Chung_cu', 'Loai_hinh_can_ho__Can_ho_dich_vu__mini', 'Loai_hinh_can_ho__Duplex', 'Loai_hinh_can_ho__Officetel', 'Loai_hinh_can_ho__Penthouse', 'Loai_hinh_can_ho__Tap_the__cu_xa', 'Huong_ban_cong__Bac', 'Huong_ban_cong__Nam', 'Huong_ban_cong__Tay', 'Huong_ban_cong__Tay_Bac', 'Huong_ban_cong__Tay_Nam', 'Huong_ban_cong__Dong', 'Huong_ban_cong__Dong_Bac', 'Huong_ban_cong__Dong_Nam', 'Dac_diem_can_ho__Can_goc', 'Loai_hinh_van_phong__Mat_bang_kinh_doanh', 'Loai_hinh_van_phong__Shophouse', 'Loai_hinh_van_phong__Van_phong', 'district_chau_thanh', 'district_huyen_an_duong', 'district_huyen_bau_bang', 'district_huyen_binh_chanh', 'district_huyen_binh_son', 'district_huyen_binh_dai', 'district_huyen_bao_lam', 'district_huyen_bac_tan_uyen', 'district_huyen_ben_luc', 'district_huyen_cam_lam', 'district_huyen_chau_thanh', 'district_huyen_chau_thanh_a', 'district_huyen_chau_duc', 'district_huyen_chon_thanh', 'district_huyen_chu_se', 'district_huyen_chuong_my', 'district_huyen_cho_gao', 'district_huyen_cu_lao_dung', 'district_huyen_cu_m_gar', 'district_huyen_can_giuoc', 'district_huyen_can_gio', 'district_huyen_can_duoc', 'district_huyen_cam_giang', 'district_huyen_cam_my', 'district_huyen_cu_chi', 'district_huyen_di_linh', 'district_huyen_dien_khanh', 'district_huyen_duy_xuyen', 'district_huyen_dau_tieng', 'district_huyen_gia_lam', 'district_huyen_go_cong_tay', 'district_huyen_go_dau', 'district_huyen_hiep_hoa', 'district_huyen_hoai_nhon', 'district_huyen_hoai_duc', 'district_huyen_hoang_hoa', 'district_huyen_ham_thuan_nam', 'district_huyen_hoa_thanh', 'district_huyen_hoa_vang', 'district_huyen_hoc_mon', 'district_huyen_kim_dong', 'district_huyen_ky_son', 'district_huyen_lai_vung', 'district_huyen_long_ho', 'district_huyen_long_thanh', 'district_huyen_long_dien', 'district_huyen_lam_ha', 'district_huyen_luong_son', 'district_huyen_me_linh', 'district_huyen_moc_hoa', 'district_huyen_my_tu', 'district_huyen_nghi_loc', 'district_huyen_nghia_hanh', 'district_huyen_nha_be', 'district_huyen_nhon_trach', 'district_huyen_phong_dien', 'district_huyen_phu_my', 'district_huyen_phu_giao', 'district_huyen_phu_loc', 'district_huyen_phu_quoc', 'district_huyen_phu_rieng', 'district_huyen_phu_vang', 'district_huyen_phuc_tho', 'district_huyen_phuoc_son', 'district_huyen_phung_hiep', 'district_huyen_quang_xuong', 'district_huyen_quoc_oai', 'district_huyen_quynh_luu', 'district_huyen_soc_son', 'district_huyen_tam_binh', 'district_huyen_tam_dao', 'district_huyen_thanh_oai', 'district_huyen_thanh_tri', 'district_huyen_thuan_thanh', 'district_huyen_thuy_nguyen', 'district_huyen_thuong_tin', 'district_huyen_thach_that', 'district_huyen_thanh_phu', 'district_huyen_thong_nhat', 'district_huyen_thoi_binh', 'district_huyen_thu_thua', 'district_huyen_tien_du', 'district_huyen_tieu_can', 'district_huyen_tra_on', 'district_huyen_trang_bom', 'district_huyen_trang_bang', 'district_huyen_tuy_phong', 'district_huyen_tan_thanh', 'district_huyen_tan_tru', 'district_huyen_tinh_bien', 'district_huyen_viet_yen', 'district_huyen_vinh_cuu', 'district_huyen_vinh_thanh', 'district_huyen_van_ninh', 'district_huyen_xuyen_moc', 'district_huyen_yen_phong', 'district_huyen_an_thi', 'district_huyen_dan_phuong', 'district_huyen_dong_anh', 'district_huyen_dong_hung', 'district_huyen_dong_son', 'district_huyen_don_duong', 'district_huyen_dai_loc', 'district_huyen_dat_do', 'district_huyen_dak_ha', 'district_huyen_dinh_quan', 'district_huyen_dong_phu', 'district_huyen_duc_hue', 'district_huyen_duc_hoa', 'district_quan_1', 'district_quan_10', 'district_quan_11', 'district_quan_12', 'district_quan_2', 'district_quan_3', 'district_quan_4', 'district_quan_5', 'district_quan_6', 'district_quan_7', 'district_quan_8', 'district_quan_9', 'district_quan_ba_dinh', 'district_quan_binh_thuy', 'district_quan_binh_thanh', 'district_quan_binh_tan', 'district_quan_bac_tu_liem', 'district_quan_cai_rang', 'district_quan_cau_giay', 'district_quan_cam_le', 'district_quan_duong_kinh', 'district_quan_go_vap', 'district_quan_hai_ba_trung', 'district_quan_hoan_kiem', 'district_quan_hoang_mai', 'district_quan_ha_dong', 'district_quan_hai_an', 'district_quan_hai_chau', 'district_quan_hong_bang', 'district_quan_lien_chieu', 'district_quan_long_bien', 'district_quan_le_chan', 'district_quan_nam_tu_liem', 'district_quan_ngo_quyen', 'district_quan_ngu_hanh_son', 'district_quan_ninh_kieu', 'district_quan_phu_nhuan', 'district_quan_son_tra', 'district_quan_thanh_khe', 'district_quan_thanh_xuan', 'district_quan_thu_duc', 'district_quan_tan_binh', 'district_quan_tan_phu', 'district_quan_tay_ho', 'district_quan_o_mon', 'district_quan_dong_da', 'district_quan_do_son', 'district_thanh_pho_bien_hoa', 'district_thanh_pho_buon_ma_thuot', 'district_thanh_pho_ba_ria', 'district_thanh_pho_bac_lieu', 'district_thanh_pho_bao_loc', 'district_thanh_pho_bac_giang', 'district_thanh_pho_ben_tre', 'district_thanh_pho_cam_ranh', 'district_thanh_pho_cao_lanh', 'district_thanh_pho_chau_doc', 'district_thanh_pho_ca_mau', 'district_thanh_pho_hue', 'district_thanh_pho_ha_tien', 'district_thanh_pho_hung_yen', 'district_thanh_pho_hai_duong', 'district_thanh_pho_hoi_an', 'district_thanh_pho_long_khanh', 'district_thanh_pho_long_xuyen', 'district_thanh_pho_my_tho', 'district_thanh_pho_nam_dinh', 'district_thanh_pho_nha_trang', 'district_thanh_pho_phan_rang_thap_cham', 'district_thanh_pho_phan_thiet', 'district_thanh_pho_phuc_yen', 'district_thanh_pho_pleiku', 'district_thanh_pho_qui_nhon', 'district_thanh_pho_quang_ngai', 'district_thanh_pho_rach_gia', 'district_thanh_pho_soc_trang', 'district_thanh_pho_tam_ky', 'district_thanh_pho_thanh_hoa', 'district_thanh_pho_thuan_an', 'district_thanh_pho_thai_binh', 'district_thanh_pho_thu_dau_mot', 'district_thanh_pho_tra_vinh', 'district_thanh_pho_tan_an', 'district_thanh_pho_tay_ninh', 'district_thanh_pho_vinh', 'district_thanh_pho_vinh_long', 'district_thanh_pho_vinh_yen', 'district_thanh_pho_vung_tau', 'district_thanh_pho_vi_thanh', 'district_thanh_pho_da_lat', 'district_thanh_pho_dong_xoai', 'district_thi_xa_buon_ho', 'district_thi_xa_binh_minh', 'district_thi_xa_ben_cat', 'district_thi_xa_cai_lay', 'district_thi_xa_di_an', 'district_thi_xa_gia_nghia', 'district_thi_xa_gia_rai', 'district_thi_xa_go_cong', 'district_thi_xa_huong_thuy', 'district_thi_xa_my_hao', 'district_thi_xa_nga_bay', 'district_thi_xa_ninh_hoa', 'district_thi_xa_phu_my', 'district_thi_xa_son_tay', 'district_thi_xa_thuan_an', 'district_thi_xa_tan_uyen', 'district_thi_xa_tu_son', 'district_thi_xa_dien_ban', 'district_tp_tan_an', 'city_an_giang', 'city_ba_ria___vung_tau', 'city_binh_duong', 'city_binh_duong_', 'city_binh_phuoc', 'city_binh_thuan', 'city_binh_dinh', 'city_bac_lieu', 'city_bac_giang', 'city_bac_ninh', 'city_ben_tre', 'city_ca_mau', 'city_can_tho', 'city_gia_lai', 'city_hcm', 'city_ha_noi', 'city_hoa_binh', 'city_hung_yen', 'city_hai_duong', 'city_hai_phong', 'city_hau_giang', 'city_ho_chi_minh', 'city_khanh_hoa', 'city_kien_giang', 'city_kon_tum', 'city_long_an', 'city_lam_dong', 'city_nam_dinh', 'city_nghe_an', 'city_ninh_thuan', 'city_quang_nam', 'city_quang_ngai', 'city_quan_8', 'city_soc_trang', 'city_thanh_hoa', 'city_thanh_pho_soc_trang', 'city_thai_binh', 'city_thua_thien_hue', 'city_tien_giang', 'city_tp_ho_chi_minh', 'city_tp_my_tho_tien_giang', 'city_tp_hcm', 'city_tra_vinh', 'city_tay_ninh', 'city_tinh_binh_duong_', 'city_tinh_long_an', 'city_tinh_lo_8', 'city_tinh_lo_824', 'city_tinh_lo_911', 'city_tinh_lo_919', 'city_tinh_tra_vinh', 'city_vinh_long', 'city_vinh_phuc', 'city_da_nang', 'city_dak_lak', 'city_dak_nong', 'city_dong_nai', 'city_dong_thap', 'Phan_khu_Lo_Block_Thap_A', 'Phan_khu_Lo_Block_Thap_A_B', 'Phan_khu_Lo_Block_Thap_A_BLOCK', 'Phan_khu_Lo_Block_Thap_A1', 'Phan_khu_Lo_Block_Thap_A12', 'Phan_khu_Lo_Block_Thap_A2', 'Phan_khu_Lo_Block_Thap_A20', 'Phan_khu_Lo_Block_Thap_A3', 'Phan_khu_Lo_Block_Thap_A35', 'Phan_khu_Lo_Block_Thap_A5', 'Phan_khu_Lo_Block_Thap_A8', 'Phan_khu_Lo_Block_Thap_A81', 'Phan_khu_Lo_Block_Thap_B', 'Phan_khu_Lo_Block_Thap_B_BLOCK', 'Phan_khu_Lo_Block_Thap_B_LO', 'Phan_khu_Lo_Block_Thap_B1', 'Phan_khu_Lo_Block_Thap_B2', 'Phan_khu_Lo_Block_Thap_B3', 'Phan_khu_Lo_Block_Thap_B3_BLOCK', 'Phan_khu_Lo_Block_Thap_B4', 'Phan_khu_Lo_Block_Thap_B7', 'Phan_khu_Lo_Block_Thap_BLOCK_LK22', 'Phan_khu_Lo_Block_Thap_BLOCK_P', 'Phan_khu_Lo_Block_Thap_C', 'Phan_khu_Lo_Block_Thap_C2', 'Phan_khu_Lo_Block_Thap_D', 'Phan_khu_Lo_Block_Thap_D1', 'Phan_khu_Lo_Block_Thap_D10', 'Phan_khu_Lo_Block_Thap_D2', 'Phan_khu_Lo_Block_Thap_D36', 'Phan_khu_Lo_Block_Thap_D4', 'Phan_khu_Lo_Block_Thap_DU_AN_CENTANA_DIEN_PHUC_THANH', 'Phan_khu_Lo_Block_Thap_DU_AN_KHU_NGHI_DUONG_BAI_DAI_PHU_QUOC', 'Phan_khu_Lo_Block_Thap_DU_AN_NAM_KHANG', 'Phan_khu_Lo_Block_Thap_E', 'Phan_khu_Lo_Block_Thap_E_LO', 'Phan_khu_Lo_Block_Thap_E2', 'Phan_khu_Lo_Block_Thap_E3', 'Phan_khu_Lo_Block_Thap_E7', 'Phan_khu_Lo_Block_Thap_F_G_H_J_K_L', 'Phan_khu_Lo_Block_Thap_F4', 'Phan_khu_Lo_Block_Thap_G', 'Phan_khu_Lo_Block_Thap_G50', 'Phan_khu_Lo_Block_Thap_GREEN_RIVERSIDE', 'Phan_khu_Lo_Block_Thap_H', 'Phan_khu_Lo_Block_Thap_H20', 'Phan_khu_Lo_Block_Thap_HOMELAND_PARADISE_VILLA', 'Phan_khu_Lo_Block_Thap_J', 'Phan_khu_Lo_Block_Thap_K', 'Phan_khu_Lo_Block_Thap_KDC', 'Phan_khu_Lo_Block_Thap_KDC_GOLD_HILL', 'Phan_khu_Lo_Block_Thap_KDC_KHANG_DIEN', 'Phan_khu_Lo_Block_Thap_KDCD', 'Phan_khu_Lo_Block_Thap_KHU_A', 'Phan_khu_Lo_Block_Thap_KHU_AN_HAI', 'Phan_khu_Lo_Block_Thap_KHU_B', 'Phan_khu_Lo_Block_Thap_KHU_C', 'Phan_khu_Lo_Block_Thap_KHU_CONG_NGHE_CAO_450_HA', 'Phan_khu_Lo_Block_Thap_KHU_DAN_CU_CAO_CAP', 'Phan_khu_Lo_Block_Thap_KHU_DAN_CU', 'Phan_khu_Lo_Block_Thap_KHU_DAN_CU', 'Phan_khu_Lo_Block_Thap_KHU_DAN_CU_AN_PHU_HUNG', 'Phan_khu_Lo_Block_Thap_KHU_DAN_CU_AN_VIEN', 'Phan_khu_Lo_Block_Thap_KHU_DAN_CU_BINH_CHUAN', 'Phan_khu_Lo_Block_Thap_KHU_DAN_CU_MARINA_CHAU_PHA', 'Phan_khu_Lo_Block_Thap_KHU_DAN_CU_MOI_BINH_MY__DI_HET_DUONG_LE_VAN_KHUONG_QUA_CAU_RACH_TRA_NHA_MINH_NAM_BEN_TAY_TRAI', 'Phan_khu_Lo_Block_Thap_KHU_DAN_CU_NINH_GIANG_CAT_LAI', 'Phan_khu_Lo_Block_Thap_KHU_DAN_CU_THANH_MY_LOI_DRAGON', 'Phan_khu_Lo_Block_Thap_KHU_DAN_CU_DONG_HOA', 'Phan_khu_Lo_Block_Thap_KHU_HOANG_HOA_THAM', 'Phan_khu_Lo_Block_Thap_KHU_PHO_2___P10___TP_MY_THO', 'Phan_khu_Lo_Block_Thap_KHU_PHO_2___P10___TP_MY_THO___TIEN_GIANG', 'Phan_khu_Lo_Block_Thap_KHU_PHO_6', 'Phan_khu_Lo_Block_Thap_KHU_SAUNA', 'Phan_khu_Lo_Block_Thap_KHU_TAI_DINH_CU_PHUONG_1', 'Phan_khu_Lo_Block_Thap_KHU_DO_THI_TRUONG_AN', 'Phan_khu_Lo_Block_Thap_KHU_DUONG_LE_VAN_QUOI_NGA_TU_4_XA', 'Phan_khu_Lo_Block_Thap_Khong_thuoc_project_block', 'Phan_khu_Lo_Block_Thap_L', 'Phan_khu_Lo_Block_Thap_LIEN_KHU_DAN_CU_THINH_VUONG', 'Phan_khu_Lo_Block_Thap_LO_N', 'Phan_khu_Lo_Block_Thap_M5', 'Phan_khu_Lo_Block_Thap_N16', 'Phan_khu_Lo_Block_Thap_PHAN_KHU_2', 'Phan_khu_Lo_Block_Thap_S1', 'Phan_khu_Lo_Block_Thap_S4', 'Phan_khu_Lo_Block_Thap_S6', 'Phan_khu_Lo_Block_Thap_S7', 'Phan_khu_Lo_Block_Thap_SAI_GON_VILLAGE', 'Phan_khu_Lo_Block_Thap_T28', 'Phan_khu_Lo_Block_Thap_T5', 'Phan_khu_Lo_Block_Thap_THANG_LONG_CITY', 'Phan_khu_Lo_Block_Thap_TAN_KIEN_RESIDENCES', 'Phan_khu_Lo_Block_Thap_W3']

# 4. Chia tập train/test

In [10]:
X = df_temp.drop(['Price__trieu_VND_','log_price'], axis=1)
Y = df_temp['log_price']

In [11]:
X

,Dien_tich_dat_,Chieu_ngang_,Chieu_dai_,So_phong_ngu_,So_phong_ve_sinh_,Dien_tich_su_dung_,Dien_tich_,Tong_so_tang_,Tang_so_,has_floor_number,...,Phan_khu_Lo_Block_Thap_S1,Phan_khu_Lo_Block_Thap_S4,Phan_khu_Lo_Block_Thap_S6,Phan_khu_Lo_Block_Thap_S7,Phan_khu_Lo_Block_Thap_SAI_GON_VILLAGE,Phan_khu_Lo_Block_Thap_T28,Phan_khu_Lo_Block_Thap_T5,Phan_khu_Lo_Block_Thap_THANG_LONG_CITY,Phan_khu_Lo_Block_Thap_TAN_KIEN_RESIDENCES,Phan_khu_Lo_Block_Thap_W3
0,170.00,13.0,13.00,2.0,2.0,40.0,103.0,1.0,26.0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,64.20,4.0,16.05,2.0,2.0,40.0,103.0,1.0,26.0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,108.00,5.0,20.00,6.0,6.0,226.0,103.0,2.0,26.0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,42.00,4.0,11.00,5.0,3.0,226.0,103.0,2.0,26.0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,93.00,5.5,17.00,5.0,6.0,226.0,103.0,5.0,26.0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5942,33.00,6.0,11.00,4.0,3.0,31.0,35.0,4.0,18.0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5943,56.00,4.0,14.50,3.0,2.0,96.0,35.0,4.0,18.0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5944,68.00,4.0,17.00,3.0,2.0,96.0,35.0,4.0,18.0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5945,68.00,4.0,17.00,1.0,1.0,96.0,36.0,4.0,18.0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5946,32.28,4.0,8.07,1.0,1.0,96.0,36.0,4.0,18.0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [12]:
X_train, X_test, Y_train, Y_test = train_test_split(
    X,Y, test_size = 0.3, random_state = 42
)

# 5. Huấn luyện mô hình

In [13]:
pipelines = {
    'linear':    [('model', LinearRegression())],
    'xgboost':   [('model', xgb.XGBRegressor(objective='reg:squarederror'))],
    'histogram': [('model', HistGradientBoostingRegressor())],
    'catboost':  [('model', CatBoostRegressor(verbose=0))],
    'lightGBM':  [('model', LGBMRegressor())]
}

In [14]:
results = []
for name, pipeline in pipelines.items():
    model = Pipeline(pipeline).fit(X_train.values, Y_train.values)
    Y_pred = model.predict(X_test.values)
    r2 = r2_score(Y_test, Y_pred)
    mse = mean_squared_error(Y_test, Y_pred)
    rmse = np.sqrt(mean_squared_error(Y_test, Y_pred))
    mae = mean_absolute_error(Y_test, Y_pred)
    results.append({
        'model': name,
        'r2': r2,
        'mse': mse,
        'rmse': rmse,
        'mae': mae,
        'model_train': model
    })

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001421 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1166
[LightGBM] [Info] Number of data points in the train set: 4162, number of used features: 150
[LightGBM] [Info] Start training from score 7.672900

/Users/nals_macbook_108/Library/Python/3.9/lib/python/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

In [16]:
pd.DataFrame(results).sort_values(by=['r2', 'mse'],
                                  ascending=[False, True]).reset_index(drop=True)

,model,r2,mse,rmse,mae,model_train
0,catboost,0.437227,0.553492,0.743971,0.539087,"(CatBoostRegressor(loss_function='RMSE', verbo..."
1,lightGBM,0.415797,0.574569,0.758003,0.544672,(LGBMRegressor())
2,histogram,0.414926,0.575425,0.758568,0.543613,(HistGradientBoostingRegressor())
3,xgboost,0.414657,0.575690,0.758742,0.542116,"(XGBRegressor(base_score=None, booster=None, c..."
4,linear,-5.102234,6.001597,2.449816,0.649415,(LinearRegression())

### Metric đánh giá 
Metric r2: tỉ lệ phương sai dữ liệu mà mô hình giải thchs được
- r2 = 1.0 --> hoàn hảo, r2 = 0 --> không tốt hơn dự đoán trung bình, r2 < 0 --> tệ hơn dự đoán trung bình

Metric rmse/mse: sai số bình phương - phạt năng các lỗi lớn

Metric mae: sai số tuyệt đối trung bình - ít bị ảnh hưởng bởi outlier
### Phân tích chi tiết
- Nhóm gradient boosting (Mô hình catboost, lightGBM, XGboost, histogram)) hoạt động tốt với r2 ~ 0.41 -> 0.43, nghĩa là mô hình giải thích được > 41,4% ~ 43.7% biến động của dữ liệu, phù hợp với dữ liệu cấu trúc phi tuyến
- Linear Regression có r2 <0 - tệ, nguyên nhân:
+ dữ liệu chưa được chuẩn hoá (scaling) - Linear Regression rất nhạy cảm với scale features
+ dữ liệu có thể có ôutpier lớn ảnh hưởng nặng

--> Phân tích tiếp nhóm Gradient Boosting, tốt nhất sử dụng model Catboost làm mô hình chính vì r2 cao nhất và mae thấp nhất (53.9).