# 1. Đọc dữ liệu

In [81]:

df = pd.read_csv('../data/preproces_data.csv')
df.head()

,Diện tích đất:,Hướng cửa chính:,Giấy tờ pháp lý:,Đặc điểm nhà/đất:,Loại hình đất:,Chiều ngang:,Chiều dài:,Số phòng ngủ:,Số phòng vệ sinh:,Loại hình nhà ở:,...,Tầng số:,Hướng ban công:,Đặc điểm căn hộ:,Loại hình văn phòng:,district,city,Phân khu/Lô/Block/Tháp,has_floor_number,Price (trieu VND),log_price
0,170.0,Tây Bắc,Đã có sổ,Mặt tiền,Đất thổ cư,13.0,13.00,2.0,2.0,"Nhà mặt phố, mặt tiền",...,26.0,Đông Bắc,Căn góc,Shophouse,thành phố tân an,long an,Không thuộc project/block,1,419.0,6.040255
1,64.2,Tây Bắc,Đã có sổ,Nở hậu,Đất thổ cư,4.0,16.05,2.0,2.0,"Nhà mặt phố, mặt tiền",...,26.0,Đông Bắc,Căn góc,Shophouse,quận 9,tp hồ chí minh,Không thuộc project/block,1,936.0,6.842683
2,108.0,Tây,Đã có sổ,Nở hậu,Đất thổ cư,5.0,20.00,6.0,6.0,"Nhà ngõ, hẻm",...,26.0,Đông Bắc,Căn góc,Shophouse,quận 7,tp hồ chí minh,Không thuộc project/block,1,9500.0,9.159152
3,42.0,Nam,Đã có sổ,Nở hậu,Đất thổ cư,4.0,11.00,5.0,3.0,"Nhà ngõ, hẻm",...,26.0,Đông Bắc,Căn góc,Shophouse,quận 11,tp hồ chí minh,Không thuộc project/block,1,6500.0,8.779711
4,93.0,Nam,Đã có sổ,Hẻm xe hơi,Đất thổ cư,5.5,17.00,5.0,6.0,"Nhà ngõ, hẻm",...,26.0,Đông Bắc,Căn góc,Shophouse,quận bình tân,tp hồ chí minh,Không thuộc project/block,1,5000.0,8.517393

In [82]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5947 entries, 0 to 5946
Data columns (total 26 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Diện tích đất:            5947 non-null   float64
 1   Hướng cửa chính:          5947 non-null   object
 2   Giấy tờ pháp lý:          5947 non-null   object
 3   Đặc điểm nhà/đất:         5947 non-null   object
 4   Loại hình đất:            5947 non-null   object
 5   Chiều ngang:              5947 non-null   float64
 6   Chiều dài:                5947 non-null   float64
 7   Số phòng ngủ:             5947 non-null   float64
 8   Số phòng vệ sinh:         5947 non-null   float64
 9   Loại hình nhà ở:          5947 non-null   object
 10  Tình trạng nội thất:      5947 non-null   object
 11  Diện tích sử dụng:        5947 non-null   float64
 12  Tình trạng bất động sản:  5947 non-null   object
 13  Diện tích:                5947 non-null   float64
 14  Loại hình căn hộ:         5947 non-null   object
 15  Tổng số tầng:             5947 non-null   float64
 16  Tầng số:                  5947 non-null   float64
 17  Hướng ban công:           5947 non-null   object
 18  Đặc điểm căn hộ:          5947 non-null   object
 19  Loại hình văn phòng:      5947 non-null   object
 20  district                  5947 non-null   object
 21  city                      5947 non-null   object
 22  Phân khu/Lô/Block/Tháp    5947 non-null   object
 23  has_floor_number          5947 non-null   int64
 24  Price (trieu VND)         5947 non-null   float64
 25  log_price                 5947 non-null   float64
dtypes: float64(11), int64(1), object(14)
memory usage: 1.2+ MB

# 2. Import thư viện sử dụng

Sử dụng 3 model:
 - lightgmb
 - catboost
 - xgboost

In [84]:
!pip install lightgbm xgboost catboost

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: lightgbm in /Users/nals_macbook_108/Library/Python/3.9/lib/python/site-packages (4.6.0)
Requirement already satisfied: xgboost in /Users/nals_macbook_108/Library/Python/3.9/lib/python/site-packages (2.1.4)
Requirement already satisfied: catboost in /Users/nals_macbook_108/Library/Python/3.9/lib/python/site-packages (1.2.10)
Requirement already satisfied: numpy>=1.17.0 in /Users/nals_macbook_108/Library/Python/3.9/lib/python/site-packages (from lightgbm) (2.0.2)
Requirement already satisfied: scipy in /Users/nals_macbook_108/Library/Python/3.9/lib/python/site-packages (from lightgbm) (1.13.1)
Requirement already satisfied: graphviz in /Users/nals_macbook_108/Library/Python/3.9/lib/python/site-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /Users/nals_macbook_108/Library/Python/3.9/lib/python/site-packages (from catboost) (3.9.3)
Requirement already satisfied: pandas<4.0,>=0.24 in /Users/nals_macbook_108/Library/Python/3.9/lib/python/site-packages (from catboost) (2.2.3)
Requirement already satisfied: plotly in /Users/nals_macbook_108/Library/Python/3.9/lib/python/site-packages (from catboost) (6.7.0)
Requirement already satisfied: six in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from catboost) (1.15.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/nals_macbook_108/Library/Python/3.9/lib/python/site-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/nals_macbook_108/Library/Python/3.9/lib/python/site-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/nals_macbook_108/Library/Python/3.9/lib/python/site-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in /Users/nals_macbook_108/Library/Python/3.9/lib/python/site-packages (from matplotlib->catboost) (1.3.0)
Requirement already satisfied: cycler>=0.10 in /Users/nals_macbook_108/Library/Python/3.9/lib/python/site-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Users/nals_macbook_108/Library/Python/3.9/lib/python/site-packages (from matplotlib->catboost) (4.59.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/nals_macbook_108/Library/Python/3.9/lib/python/site-packages (from matplotlib->catboost) (1.4.7)
Requirement already satisfied: packaging>=20.0 in /Users/nals_macbook_108/Library/Python/3.9/lib/python/site-packages (from matplotlib->catboost) (25.0)
Requirement already satisfied: pillow>=8 in /Users/nals_macbook_108/Library/Python/3.9/lib/python/site-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /Users/nals_macbook_108/Library/Python/3.9/lib/python/site-packages (from matplotlib->catboost) (3.2.3)
Requirement already satisfied: importlib-resources>=3.2.0 in /Users/nals_macbook_108/Library/Python/3.9/lib/python/site-packages (from matplotlib->catboost) (6.5.2)
Requirement already satisfied: zipp>=3.1.0 in /Users/nals_macbook_108/Library/Python/3.9/lib/python/site-packages (from importlib-resources>=3.2.0->matplotlib->catboost) (3.21.0)
Requirement already satisfied: narwhals>=1.15.1 in /Users/nals_macbook_108/Library/Python/3.9/lib/python/site-packages (from plotly->catboost) (2.13.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: /Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip

In [85]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import r2_score
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import HistGradientBoostingRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.pipeline import Pipeline
from sklearn.svm import SVR
from sklearn.preprocessing import MinMaxScaler, PolynomialFeatures, StandardScaler, Normalizer, LabelEncoder, OneHotEncoder
from catboost import CatBoostRegressor
from lightgbm import LGBMRegressor
import xgboost as xgb

# 1. One-hot endcoding với các

In [86]:
object_cols = df.loc[:, df.dtypes == object].columns # tìm các cột kiểu dữ liệu object trong dataframe

In [102]:
df_temp = df.copy()
onehot_dict = {}

for col in object_cols:
    enc = OneHotEncoder(sparse_output=False)  # bỏ luôn .toarray()
    transformed = enc.fit_transform(df_temp[col].values.reshape(-1, 1))
    onehot_dict[col] = enc
    
    # Đặt tên cột theo tên cột gốc để tránh trùng
    feature_names = [f"{col}_{cat}" for cat in enc.categories_[0]]
    ohe_df = pd.DataFrame(transformed, columns=feature_names, index=df_temp.index)
    
    df_temp = df_temp.drop([col], axis=1)
    df_temp = df_temp.join(ohe_df)

In [103]:
df_temp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5947 entries, 0 to 5946
Columns: 429 entries, dien_tich_dat to phan_khu_lo_block_thap_W3
dtypes: float64(428), int64(1)
memory usage: 19.5 MB

In [106]:
print("Số cột sau One-Hot:", df_temp.shape[1])

Số cột sau One-Hot: 429

Sau khi One-Hot Endcoding, tổng quan kết quả:
1) 429 columns: từ 29 columns ban đầu đã chuyển đổi thành 429 cột vì mỗi giá tị unique của cột chữ thành 1 cột riêng
2) 5947 mẫu dữ liệu (đáp ứng yêu cầu - tối thiểu 5000)
3) dtype gồm 2 loại: 
- float64 - 428 columns
- int64 - 1 columns

Tuy nhiên hiện tại các name column không phải ở dạng unidecode, nên XGBoost không xử lý được, cần chuyển về unidecode để phục vụ việc train data

In [108]:
from unidecode import unidecode
import re

def clean_col(col):
    col = unidecode(col)
    col = re.sub(r'[^A-Za-z0-9_]', '_', col)
    return col

df_temp.columns = [clean_col(col) for col in df_temp.columns]

print("Tên cột sau clean:", df_temp.columns.tolist()[:429])

Tên cột sau clean: ['dien_tich_dat', 'chieu_ngang', 'chieu_dai', 'so_phong_ngu', 'so_phong_ve_sinh', 'dien_tich_su_dung', 'dien_tich', 'tong_so_tang', 'tang_so', 'has_floor_number', 'price_trieu_vnd', 'log_price', 'huong_cua_chinh_Bac', 'huong_cua_chinh_Nam', 'huong_cua_chinh_Tay', 'huong_cua_chinh_Tay_Bac', 'huong_cua_chinh_Tay_Nam', 'huong_cua_chinh_Dong', 'huong_cua_chinh_Dong_Bac', 'huong_cua_chinh_Dong_Nam', 'giay_to_phap_ly_Giay_to_khac', 'giay_to_phap_ly_Dang_cho_so', 'giay_to_phap_ly_Da_co_so', 'dac_diem_nha_dat_Hem_xe_hoi', 'dac_diem_nha_dat_Mat_tien', 'dac_diem_nha_dat_No_hau', 'loai_hinh_dat_Dat_cong_nghiep', 'loai_hinh_dat_Dat_nong_nghiep', 'loai_hinh_dat_Dat_nen_du_an', 'loai_hinh_dat_Dat_tho_cu', 'loai_hinh_nha_o_Nha_biet_thu', 'loai_hinh_nha_o_Nha_mat_pho__mat_tien', 'loai_hinh_nha_o_Nha_ngo__hem', 'loai_hinh_nha_o_Nha_pho_lien_ke', 'tinh_trang_noi_that_Ban_giao_tho', 'tinh_trang_noi_that_Hoan_thien_co_ban', 'tinh_trang_noi_that_Noi_that_cao_cap', 'tinh_trang_noi_that_Noi_that_day_du', 'tinh_trang_bat_dong_san_Chua_ban_giao', 'tinh_trang_bat_dong_san_Da_ban_giao', 'loai_hinh_can_ho_Chung_cu', 'loai_hinh_can_ho_Can_ho_dich_vu__mini', 'loai_hinh_can_ho_Duplex', 'loai_hinh_can_ho_Officetel', 'loai_hinh_can_ho_Penthouse', 'loai_hinh_can_ho_Tap_the__cu_xa', 'huong_ban_cong_Bac', 'huong_ban_cong_Nam', 'huong_ban_cong_Tay', 'huong_ban_cong_Tay_Bac', 'huong_ban_cong_Tay_Nam', 'huong_ban_cong_Dong', 'huong_ban_cong_Dong_Bac', 'huong_ban_cong_Dong_Nam', 'dac_diem_can_ho_Can_goc', 'loai_hinh_van_phong_Mat_bang_kinh_doanh', 'loai_hinh_van_phong_Shophouse', 'loai_hinh_van_phong_Van_phong', 'district_chau_thanh', 'district_huyen_an_duong', 'district_huyen_bau_bang', 'district_huyen_binh_chanh', 'district_huyen_binh_son', 'district_huyen_binh_dai', 'district_huyen_bao_lam', 'district_huyen_bac_tan_uyen', 'district_huyen_ben_luc', 'district_huyen_cam_lam', 'district_huyen_chau_thanh', 'district_huyen_chau_thanh_a', 'district_huyen_chau_duc', 'district_huyen_chon_thanh', 'district_huyen_chu_se', 'district_huyen_chuong_my', 'district_huyen_cho_gao', 'district_huyen_cu_lao_dung', 'district_huyen_cu_m_gar', 'district_huyen_can_giuoc', 'district_huyen_can_gio', 'district_huyen_can_duoc', 'district_huyen_cam_giang', 'district_huyen_cam_my', 'district_huyen_cu_chi', 'district_huyen_di_linh', 'district_huyen_dien_khanh', 'district_huyen_duy_xuyen', 'district_huyen_dau_tieng', 'district_huyen_gia_lam', 'district_huyen_go_cong_tay', 'district_huyen_go_dau', 'district_huyen_hiep_hoa', 'district_huyen_hoai_nhon', 'district_huyen_hoai_duc', 'district_huyen_hoang_hoa', 'district_huyen_ham_thuan_nam', 'district_huyen_hoa_thanh', 'district_huyen_hoa_vang', 'district_huyen_hoc_mon', 'district_huyen_kim_dong', 'district_huyen_ky_son', 'district_huyen_lai_vung', 'district_huyen_long_ho', 'district_huyen_long_thanh', 'district_huyen_long_dien', 'district_huyen_lam_ha', 'district_huyen_luong_son', 'district_huyen_me_linh', 'district_huyen_moc_hoa', 'district_huyen_my_tu', 'district_huyen_nghi_loc', 'district_huyen_nghia_hanh', 'district_huyen_nha_be', 'district_huyen_nhon_trach', 'district_huyen_phong_dien', 'district_huyen_phu_my', 'district_huyen_phu_giao', 'district_huyen_phu_loc', 'district_huyen_phu_quoc', 'district_huyen_phu_rieng', 'district_huyen_phu_vang', 'district_huyen_phuc_tho', 'district_huyen_phuoc_son', 'district_huyen_phung_hiep', 'district_huyen_quang_xuong', 'district_huyen_quoc_oai', 'district_huyen_quynh_luu', 'district_huyen_soc_son', 'district_huyen_tam_binh', 'district_huyen_tam_dao', 'district_huyen_thanh_oai', 'district_huyen_thanh_tri', 'district_huyen_thuan_thanh', 'district_huyen_thuy_nguyen', 'district_huyen_thuong_tin', 'district_huyen_thach_that', 'district_huyen_thanh_phu', 'district_huyen_thong_nhat', 'district_huyen_thoi_binh', 'district_huyen_thu_thua', 'district_huyen_tien_du', 'district_huyen_tieu_can', 'district_huyen_tra_on', 'district_huyen_trang_bom', 'district_huyen_trang_bang', 'district_huyen_tuy_phong', 'district_huyen_tan_thanh', 'district_huyen_tan_tru', 'district_huyen_tinh_bien', 'district_huyen_viet_yen', 'district_huyen_vinh_cuu', 'district_huyen_vinh_thanh', 'district_huyen_van_ninh', 'district_huyen_xuyen_moc', 'district_huyen_yen_phong', 'district_huyen_an_thi', 'district_huyen_dan_phuong', 'district_huyen_dong_anh', 'district_huyen_dong_hung', 'district_huyen_dong_son', 'district_huyen_don_duong', 'district_huyen_dai_loc', 'district_huyen_dat_do', 'district_huyen_dak_ha', 'district_huyen_dinh_quan', 'district_huyen_dong_phu', 'district_huyen_duc_hue', 'district_huyen_duc_hoa', 'district_quan_1', 'district_quan_10', 'district_quan_11', 'district_quan_12', 'district_quan_2', 'district_quan_3', 'district_quan_4', 'district_quan_5', 'district_quan_6', 'district_quan_7', 'district_quan_8', 'district_quan_9', 'district_quan_ba_dinh', 'district_quan_binh_thuy', 'district_quan_binh_thanh', 'district_quan_binh_tan', 'district_quan_bac_tu_liem', 'district_quan_cai_rang', 'district_quan_cau_giay', 'district_quan_cam_le', 'district_quan_duong_kinh', 'district_quan_go_vap', 'district_quan_hai_ba_trung', 'district_quan_hoan_kiem', 'district_quan_hoang_mai', 'district_quan_ha_dong', 'district_quan_hai_an', 'district_quan_hai_chau', 'district_quan_hong_bang', 'district_quan_lien_chieu', 'district_quan_long_bien', 'district_quan_le_chan', 'district_quan_nam_tu_liem', 'district_quan_ngo_quyen', 'district_quan_ngu_hanh_son', 'district_quan_ninh_kieu', 'district_quan_phu_nhuan', 'district_quan_son_tra', 'district_quan_thanh_khe', 'district_quan_thanh_xuan', 'district_quan_thu_duc', 'district_quan_tan_binh', 'district_quan_tan_phu', 'district_quan_tay_ho', 'district_quan_o_mon', 'district_quan_dong_da', 'district_quan_do_son', 'district_thanh_pho_bien_hoa', 'district_thanh_pho_buon_ma_thuot', 'district_thanh_pho_ba_ria', 'district_thanh_pho_bac_lieu', 'district_thanh_pho_bao_loc', 'district_thanh_pho_bac_giang', 'district_thanh_pho_ben_tre', 'district_thanh_pho_cam_ranh', 'district_thanh_pho_cao_lanh', 'district_thanh_pho_chau_doc', 'district_thanh_pho_ca_mau', 'district_thanh_pho_hue', 'district_thanh_pho_ha_tien', 'district_thanh_pho_hung_yen', 'district_thanh_pho_hai_duong', 'district_thanh_pho_hoi_an', 'district_thanh_pho_long_khanh', 'district_thanh_pho_long_xuyen', 'district_thanh_pho_my_tho', 'district_thanh_pho_nam_dinh', 'district_thanh_pho_nha_trang', 'district_thanh_pho_phan_rang_thap_cham', 'district_thanh_pho_phan_thiet', 'district_thanh_pho_phuc_yen', 'district_thanh_pho_pleiku', 'district_thanh_pho_qui_nhon', 'district_thanh_pho_quang_ngai', 'district_thanh_pho_rach_gia', 'district_thanh_pho_soc_trang', 'district_thanh_pho_tam_ky', 'district_thanh_pho_thanh_hoa', 'district_thanh_pho_thuan_an', 'district_thanh_pho_thai_binh', 'district_thanh_pho_thu_dau_mot', 'district_thanh_pho_tra_vinh', 'district_thanh_pho_tan_an', 'district_thanh_pho_tay_ninh', 'district_thanh_pho_vinh', 'district_thanh_pho_vinh_long', 'district_thanh_pho_vinh_yen', 'district_thanh_pho_vung_tau', 'district_thanh_pho_vi_thanh', 'district_thanh_pho_da_lat', 'district_thanh_pho_dong_xoai', 'district_thi_xa_buon_ho', 'district_thi_xa_binh_minh', 'district_thi_xa_ben_cat', 'district_thi_xa_cai_lay', 'district_thi_xa_di_an', 'district_thi_xa_gia_nghia', 'district_thi_xa_gia_rai', 'district_thi_xa_go_cong', 'district_thi_xa_huong_thuy', 'district_thi_xa_my_hao', 'district_thi_xa_nga_bay', 'district_thi_xa_ninh_hoa', 'district_thi_xa_phu_my', 'district_thi_xa_son_tay', 'district_thi_xa_thuan_an', 'district_thi_xa_tan_uyen', 'district_thi_xa_tu_son', 'district_thi_xa_dien_ban', 'district_tp_tan_an', 'city_an_giang', 'city_ba_ria___vung_tau', 'city_binh_duong', 'city_binh_duong_', 'city_binh_phuoc', 'city_binh_thuan', 'city_binh_dinh', 'city_bac_lieu', 'city_bac_giang', 'city_bac_ninh', 'city_ben_tre', 'city_ca_mau', 'city_can_tho', 'city_gia_lai', 'city_hcm', 'city_ha_noi', 'city_hoa_binh', 'city_hung_yen', 'city_hai_duong', 'city_hai_phong', 'city_hau_giang', 'city_ho_chi_minh', 'city_khanh_hoa', 'city_kien_giang', 'city_kon_tum', 'city_long_an', 'city_lam_dong', 'city_nam_dinh', 'city_nghe_an', 'city_ninh_thuan', 'city_quang_nam', 'city_quang_ngai', 'city_quan_8', 'city_soc_trang', 'city_thanh_hoa', 'city_thanh_pho_soc_trang', 'city_thai_binh', 'city_thua_thien_hue', 'city_tien_giang', 'city_tp_ho_chi_minh', 'city_tp_my_tho_tien_giang', 'city_tp_hcm', 'city_tra_vinh', 'city_tay_ninh', 'city_tinh_binh_duong_', 'city_tinh_long_an', 'city_tinh_lo_8', 'city_tinh_lo_824', 'city_tinh_lo_911', 'city_tinh_lo_919', 'city_tinh_tra_vinh', 'city_vinh_long', 'city_vinh_phuc', 'city_da_nang', 'city_dak_lak', 'city_dak_nong', 'city_dong_nai', 'city_dong_thap', 'phan_khu_lo_block_thap_A', 'phan_khu_lo_block_thap_A_B', 'phan_khu_lo_block_thap_A_BLOCK', 'phan_khu_lo_block_thap_A1', 'phan_khu_lo_block_thap_A12', 'phan_khu_lo_block_thap_A2', 'phan_khu_lo_block_thap_A20', 'phan_khu_lo_block_thap_A3', 'phan_khu_lo_block_thap_A35', 'phan_khu_lo_block_thap_A5', 'phan_khu_lo_block_thap_A8', 'phan_khu_lo_block_thap_A81', 'phan_khu_lo_block_thap_B', 'phan_khu_lo_block_thap_B_BLOCK', 'phan_khu_lo_block_thap_B_LO', 'phan_khu_lo_block_thap_B1', 'phan_khu_lo_block_thap_B2', 'phan_khu_lo_block_thap_B3', 'phan_khu_lo_block_thap_B3_BLOCK', 'phan_khu_lo_block_thap_B4', 'phan_khu_lo_block_thap_B7', 'phan_khu_lo_block_thap_BLOCK_LK22', 'phan_khu_lo_block_thap_BLOCK_P', 'phan_khu_lo_block_thap_C', 'phan_khu_lo_block_thap_C2', 'phan_khu_lo_block_thap_D', 'phan_khu_lo_block_thap_D1', 'phan_khu_lo_block_thap_D10', 'phan_khu_lo_block_thap_D2', 'phan_khu_lo_block_thap_D36', 'phan_khu_lo_block_thap_D4', 'phan_khu_lo_block_thap_DU_AN_CENTANA_DIEN_PHUC_THANH', 'phan_khu_lo_block_thap_DU_AN_KHU_NGHI_DUONG_BAI_DAI_PHU_QUOC', 'phan_khu_lo_block_thap_DU_AN_NAM_KHANG', 'phan_khu_lo_block_thap_E', 'phan_khu_lo_block_thap_E_LO', 'phan_khu_lo_block_thap_E2', 'phan_khu_lo_block_thap_E3', 'phan_khu_lo_block_thap_E7', 'phan_khu_lo_block_thap_F_G_H_J_K_L', 'phan_khu_lo_block_thap_F4', 'phan_khu_lo_block_thap_G', 'phan_khu_lo_block_thap_G50', 'phan_khu_lo_block_thap_GREEN_RIVERSIDE', 'phan_khu_lo_block_thap_H', 'phan_khu_lo_block_thap_H20', 'phan_khu_lo_block_thap_HOMELAND_PARADISE_VILLA', 'phan_khu_lo_block_thap_J', 'phan_khu_lo_block_thap_K', 'phan_khu_lo_block_thap_KDC', 'phan_khu_lo_block_thap_KDC_GOLD_HILL', 'phan_khu_lo_block_thap_KDC_KHANG_DIEN', 'phan_khu_lo_block_thap_KDCD', 'phan_khu_lo_block_thap_KHU_A', 'phan_khu_lo_block_thap_KHU_AN_HAI', 'phan_khu_lo_block_thap_KHU_B', 'phan_khu_lo_block_thap_KHU_C', 'phan_khu_lo_block_thap_KHU_CONG_NGHE_CAO_450_HA', 'phan_khu_lo_block_thap_KHU_DAN_CU_CAO_CAP', 'phan_khu_lo_block_thap_KHU_DAN_CU', 'phan_khu_lo_block_thap_KHU_DAN_CU', 'phan_khu_lo_block_thap_KHU_DAN_CU_AN_PHU_HUNG', 'phan_khu_lo_block_thap_KHU_DAN_CU_AN_VIEN', 'phan_khu_lo_block_thap_KHU_DAN_CU_BINH_CHUAN', 'phan_khu_lo_block_thap_KHU_DAN_CU_MARINA_CHAU_PHA', 'phan_khu_lo_block_thap_KHU_DAN_CU_MOI_BINH_MY__DI_HET_DUONG_LE_VAN_KHUONG_QUA_CAU_RACH_TRA_NHA_MINH_NAM_BEN_TAY_TRAI', 'phan_khu_lo_block_thap_KHU_DAN_CU_NINH_GIANG_CAT_LAI', 'phan_khu_lo_block_thap_KHU_DAN_CU_THANH_MY_LOI_DRAGON', 'phan_khu_lo_block_thap_KHU_DAN_CU_DONG_HOA', 'phan_khu_lo_block_thap_KHU_HOANG_HOA_THAM', 'phan_khu_lo_block_thap_KHU_PHO_2___P10___TP_MY_THO', 'phan_khu_lo_block_thap_KHU_PHO_2___P10___TP_MY_THO___TIEN_GIANG', 'phan_khu_lo_block_thap_KHU_PHO_6', 'phan_khu_lo_block_thap_KHU_SAUNA', 'phan_khu_lo_block_thap_KHU_TAI_DINH_CU_PHUONG_1', 'phan_khu_lo_block_thap_KHU_DO_THI_TRUONG_AN', 'phan_khu_lo_block_thap_KHU_DUONG_LE_VAN_QUOI_NGA_TU_4_XA', 'phan_khu_lo_block_thap_Khong_thuoc_project_block', 'phan_khu_lo_block_thap_L', 'phan_khu_lo_block_thap_LIEN_KHU_DAN_CU_THINH_VUONG', 'phan_khu_lo_block_thap_LO_N', 'phan_khu_lo_block_thap_M5', 'phan_khu_lo_block_thap_N16', 'phan_khu_lo_block_thap_PHAN_KHU_2', 'phan_khu_lo_block_thap_S1', 'phan_khu_lo_block_thap_S4', 'phan_khu_lo_block_thap_S6', 'phan_khu_lo_block_thap_S7', 'phan_khu_lo_block_thap_SAI_GON_VILLAGE', 'phan_khu_lo_block_thap_T28', 'phan_khu_lo_block_thap_T5', 'phan_khu_lo_block_thap_THANG_LONG_CITY', 'phan_khu_lo_block_thap_TAN_KIEN_RESIDENCES', 'phan_khu_lo_block_thap_W3']

# 4. Chia tập train/test

In [109]:
X = df_temp.drop('price_trieu_vnd', axis=1)
Y = df_temp['price_trieu_vnd']

In [110]:
X

,dien_tich_dat,chieu_ngang,chieu_dai,so_phong_ngu,so_phong_ve_sinh,dien_tich_su_dung,dien_tich,tong_so_tang,tang_so,has_floor_number,...,phan_khu_lo_block_thap_S1,phan_khu_lo_block_thap_S4,phan_khu_lo_block_thap_S6,phan_khu_lo_block_thap_S7,phan_khu_lo_block_thap_SAI_GON_VILLAGE,phan_khu_lo_block_thap_T28,phan_khu_lo_block_thap_T5,phan_khu_lo_block_thap_THANG_LONG_CITY,phan_khu_lo_block_thap_TAN_KIEN_RESIDENCES,phan_khu_lo_block_thap_W3
0,170.00,13.0,13.00,2.0,2.0,40.0,103.0,1.0,26.0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,64.20,4.0,16.05,2.0,2.0,40.0,103.0,1.0,26.0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,108.00,5.0,20.00,6.0,6.0,226.0,103.0,2.0,26.0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,42.00,4.0,11.00,5.0,3.0,226.0,103.0,2.0,26.0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,93.00,5.5,17.00,5.0,6.0,226.0,103.0,5.0,26.0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5942,33.00,6.0,11.00,4.0,3.0,31.0,35.0,4.0,18.0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5943,56.00,4.0,14.50,3.0,2.0,96.0,35.0,4.0,18.0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5944,68.00,4.0,17.00,3.0,2.0,96.0,35.0,4.0,18.0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5945,68.00,4.0,17.00,1.0,1.0,96.0,36.0,4.0,18.0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5946,32.28,4.0,8.07,1.0,1.0,96.0,36.0,4.0,18.0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [111]:
X_train, X_test, Y_train, Y_test = train_test_split(
    X,Y, test_size = 0.3, random_state = 42
)

# 5. Huấn luyện mô hình

In [112]:

pipelines = {
    'linear': [('model', LinearRegression())],
    'xgboost': [('model',xgb.XGBRegressor(
    objective='reg:squarederror',  # for regression
    ))],
    'histogram': [('model',HistGradientBoostingRegressor())],
    'catboost': [('model',CatBoostRegressor())],
    'SVR_linear': [('model',SVR(kernel='linear'))],
    'SVR_poly': [('model',SVR(kernel='poly'))],
    'SVR_rbf': [('model',SVR(kernel='rbf'))],
    'lightGBM': [('model',LGBMRegressor())]
}

In [115]:
results = []
for name, pipeline in pipelines.items():
    model = Pipeline(pipeline).fit(X_train.values, Y_train.values)
    Y_pred = model.predict(X_test.values)
    r2 = r2_score(Y_test, Y_pred)
    mse = mean_squared_error(Y_test, Y_pred)
    rmse = np.sqrt(mean_squared_error(Y_test, Y_pred))
    mae = mean_absolute_error(Y_test, Y_pred)
    results.append({
        'model': name,
        'r2': r2,
        'mse': mse,
        'rmse': rmse,
        'mae': mae,
        'model_train': model
    })

Learning rate set to 0.05129
0:	learn: 3192.6363014	total: 6.1ms	remaining: 6.1s
1:	learn: 3056.0911465	total: 8.49ms	remaining: 4.24s
2:	learn: 2927.6935982	total: 11.5ms	remaining: 3.81s
3:	learn: 2797.7499355	total: 13.8ms	remaining: 3.43s
4:	learn: 2684.6924120	total: 16ms	remaining: 3.17s
5:	learn: 2568.9294819	total: 18.4ms	remaining: 3.04s
6:	learn: 2456.7183798	total: 21.1ms	remaining: 2.99s
7:	learn: 2354.3088627	total: 23.4ms	remaining: 2.9s
8:	learn: 2251.0831884	total: 25.8ms	remaining: 2.84s
9:	learn: 2153.9488409	total: 28.5ms	remaining: 2.82s
10:	learn: 2055.4962017	total: 30.5ms	remaining: 2.74s
11:	learn: 1975.7973060	total: 32.5ms	remaining: 2.68s
12:	learn: 1892.2314150	total: 34.3ms	remaining: 2.6s
13:	learn: 1808.9820541	total: 36.6ms	remaining: 2.58s
14:	learn: 1737.8304292	total: 38.4ms	remaining: 2.52s
15:	learn: 1662.7804375	total: 40.3ms	remaining: 2.48s
16:	learn: 1589.0270554	total: 42.5ms	remaining: 2.46s
17:	learn: 1519.1837918	total: 44.7ms	remaining: 2.44s
18:	learn: 1454.2158389	total: 46.9ms	remaining: 2.42s
19:	learn: 1397.6727020	total: 48.7ms	remaining: 2.38s
20:	learn: 1340.1698236	total: 51.1ms	remaining: 2.38s
21:	learn: 1284.3563083	total: 53ms	remaining: 2.35s
22:	learn: 1227.6023873	total: 54.8ms	remaining: 2.33s
23:	learn: 1177.8142098	total: 56.8ms	remaining: 2.31s
24:	learn: 1125.7085298	total: 59ms	remaining: 2.3s
25:	learn: 1077.9481121	total: 61.6ms	remaining: 2.31s
26:	learn: 1029.6144933	total: 63.6ms	remaining: 2.29s
27:	learn: 987.6142871	total: 65.7ms	remaining: 2.28s
28:	learn: 946.5798937	total: 67.9ms	remaining: 2.27s
29:	learn: 907.4674702	total: 69.9ms	remaining: 2.26s
30:	learn: 870.7115136	total: 72ms	remaining: 2.25s
31:	learn: 834.7749584	total: 74.1ms	remaining: 2.24s
32:	learn: 799.6295085	total: 76.3ms	remaining: 2.23s
33:	learn: 765.4606771	total: 78.2ms	remaining: 2.22s
34:	learn: 734.0728988	total: 80.4ms	remaining: 2.22s
35:	learn: 702.2486879	total: 82.4ms	remaining: 2.21s
36:	learn: 671.9683629	total: 84.2ms	remaining: 2.19s
37:	learn: 643.2701592	total: 86ms	remaining: 2.18s
38:	learn: 616.3384341	total: 87.8ms	remaining: 2.16s
39:	learn: 591.1019607	total: 89.9ms	remaining: 2.16s
40:	learn: 569.0869759	total: 92.2ms	remaining: 2.15s
41:	learn: 547.0762617	total: 93.8ms	remaining: 2.14s
42:	learn: 523.9241044	total: 95.7ms	remaining: 2.13s
43:	learn: 502.1083035	total: 97.7ms	remaining: 2.12s
44:	learn: 481.4084873	total: 99.7ms	remaining: 2.11s
45:	learn: 463.1073176	total: 102ms	remaining: 2.11s
46:	learn: 444.5058125	total: 103ms	remaining: 2.09s
47:	learn: 427.7869657	total: 105ms	remaining: 2.08s
48:	learn: 410.0883627	total: 107ms	remaining: 2.08s
49:	learn: 395.9325331	total: 109ms	remaining: 2.07s
50:	learn: 383.1340168	total: 111ms	remaining: 2.06s
51:	learn: 369.6871354	total: 113ms	remaining: 2.06s
52:	learn: 356.0910213	total: 115ms	remaining: 2.05s
53:	learn: 341.6152943	total: 117ms	remaining: 2.05s
54:	learn: 328.4751791	total: 118ms	remaining: 2.04s
55:	learn: 315.8105470	total: 120ms	remaining: 2.02s
56:	learn: 304.4834506	total: 122ms	remaining: 2.02s
57:	learn: 293.0387305	total: 124ms	remaining: 2.02s
58:	learn: 282.6144976	total: 126ms	remaining: 2.01s
59:	learn: 273.1075940	total: 128ms	remaining: 2s
60:	learn: 264.4036977	total: 130ms	remaining: 2s
61:	learn: 255.2325687	total: 132ms	remaining: 2s
62:	learn: 245.6767020	total: 134ms	remaining: 1.99s
63:	learn: 237.1805216	total: 135ms	remaining: 1.98s
64:	learn: 228.7906001	total: 137ms	remaining: 1.97s
65:	learn: 221.5742502	total: 139ms	remaining: 1.97s
66:	learn: 215.8154053	total: 141ms	remaining: 1.96s
67:	learn: 208.7284636	total: 143ms	remaining: 1.96s
68:	learn: 202.0188518	total: 145ms	remaining: 1.95s
69:	learn: 196.0569849	total: 147ms	remaining: 1.95s
70:	learn: 189.6817322	total: 149ms	remaining: 1.94s
71:	learn: 184.0687751	total: 150ms	remaining: 1.93s
72:	learn: 178.3725349	total: 152ms	remaining: 1.93s
73:	learn: 173.1055715	total: 153ms	remaining: 1.92s
74:	learn: 168.3767252	total: 156ms	remaining: 1.92s
75:	learn: 164.0836060	total: 158ms	remaining: 1.92s
76:	learn: 160.0727608	total: 159ms	remaining: 1.91s
77:	learn: 156.1154306	total: 161ms	remaining: 1.9s
78:	learn: 152.1074793	total: 163ms	remaining: 1.9s
79:	learn: 148.2138652	total: 165ms	remaining: 1.9s
80:	learn: 144.7606004	total: 167ms	remaining: 1.9s
81:	learn: 141.3172705	total: 169ms	remaining: 1.89s
82:	learn: 138.4521889	total: 171ms	remaining: 1.89s
83:	learn: 135.5093825	total: 172ms	remaining: 1.88s
84:	learn: 132.4510152	total: 174ms	remaining: 1.87s
85:	learn: 129.8621227	total: 175ms	remaining: 1.86s
86:	learn: 127.3107143	total: 177ms	remaining: 1.85s
87:	learn: 125.3978810	total: 179ms	remaining: 1.85s
88:	learn: 123.6180528	total: 180ms	remaining: 1.84s
89:	learn: 121.3534405	total: 182ms	remaining: 1.84s
90:	learn: 119.4464189	total: 186ms	remaining: 1.85s
91:	learn: 117.5151828	total: 188ms	remaining: 1.85s
92:	learn: 115.5039128	total: 190ms	remaining: 1.85s
93:	learn: 113.6638645	total: 192ms	remaining: 1.85s
94:	learn: 111.9907481	total: 194ms	remaining: 1.85s
95:	learn: 110.3264780	total: 196ms	remaining: 1.85s
96:	learn: 108.7994393	total: 199ms	remaining: 1.85s
97:	learn: 107.4082707	total: 204ms	remaining: 1.88s
98:	learn: 106.0114727	total: 206ms	remaining: 1.87s
99:	learn: 104.7168498	total: 208ms	remaining: 1.87s
100:	learn: 103.5099819	total: 210ms	remaining: 1.87s
101:	learn: 102.4158516	total: 214ms	remaining: 1.88s
102:	learn: 101.2726337	total: 216ms	remaining: 1.88s
103:	learn: 100.1515517	total: 220ms	remaining: 1.9s
104:	learn: 99.1140101	total: 223ms	remaining: 1.9s
105:	learn: 98.2360731	total: 225ms	remaining: 1.9s
106:	learn: 97.4280632	total: 228ms	remaining: 1.9s
107:	learn: 96.6355569	total: 230ms	remaining: 1.9s
108:	learn: 95.5578782	total: 232ms	remaining: 1.9s
109:	learn: 94.8769725	total: 234ms	remaining: 1.89s
110:	learn: 94.1048123	total: 236ms	remaining: 1.89s
111:	learn: 93.3665191	total: 238ms	remaining: 1.89s
112:	learn: 92.7391157	total: 240ms	remaining: 1.88s
113:	learn: 92.0333362	total: 242ms	remaining: 1.88s
114:	learn: 91.5385409	total: 244ms	remaining: 1.88s
115:	learn: 90.9669576	total: 246ms	remaining: 1.88s
116:	learn: 90.4712579	total: 248ms	remaining: 1.87s
117:	learn: 89.8763230	total: 250ms	remaining: 1.87s
118:	learn: 89.3585796	total: 252ms	remaining: 1.87s
119:	learn: 88.7520219	total: 254ms	remaining: 1.86s
120:	learn: 88.2612677	total: 256ms	remaining: 1.86s
121:	learn: 87.8265037	total: 258ms	remaining: 1.85s
122:	learn: 87.4131507	total: 260ms	remaining: 1.85s
123:	learn: 87.0252208	total: 261ms	remaining: 1.85s
124:	learn: 86.4452668	total: 264ms	remaining: 1.85s
125:	learn: 86.0741728	total: 266ms	remaining: 1.84s
126:	learn: 85.8658041	total: 267ms	remaining: 1.84s
127:	learn: 85.5781388	total: 269ms	remaining: 1.83s
128:	learn: 85.1776766	total: 271ms	remaining: 1.83s
129:	learn: 84.8150412	total: 272ms	remaining: 1.82s
130:	learn: 84.1257748	total: 274ms	remaining: 1.82s
131:	learn: 83.8146487	total: 276ms	remaining: 1.81s
132:	learn: 83.5742164	total: 278ms	remaining: 1.81s
133:	learn: 83.2669020	total: 280ms	remaining: 1.81s
134:	learn: 82.8880056	total: 281ms	remaining: 1.8s
135:	learn: 82.5397054	total: 283ms	remaining: 1.79s
136:	learn: 82.2774407	total: 284ms	remaining: 1.79s
137:	learn: 81.9676404	total: 286ms	remaining: 1.79s
138:	learn: 81.5416392	total: 288ms	remaining: 1.78s
139:	learn: 81.0928219	total: 290ms	remaining: 1.78s
140:	learn: 80.7704880	total: 292ms	remaining: 1.78s
141:	learn: 80.3612859	total: 293ms	remaining: 1.77s
142:	learn: 80.0414549	total: 296ms	remaining: 1.77s
143:	learn: 79.6623468	total: 297ms	remaining: 1.77s
144:	learn: 79.3530302	total: 299ms	remaining: 1.76s
145:	learn: 79.2419187	total: 300ms	remaining: 1.76s
146:	learn: 78.7354507	total: 302ms	remaining: 1.75s
147:	learn: 78.4829249	total: 304ms	remaining: 1.75s
148:	learn: 78.2233680	total: 305ms	remaining: 1.74s
149:	learn: 77.9962018	total: 307ms	remaining: 1.74s
150:	learn: 77.8893281	total: 309ms	remaining: 1.74s
151:	learn: 77.4385903	total: 311ms	remaining: 1.73s
152:	learn: 77.2603426	total: 313ms	remaining: 1.73s
153:	learn: 76.8232920	total: 315ms	remaining: 1.73s
154:	learn: 76.6449006	total: 317ms	remaining: 1.73s
155:	learn: 76.3731034	total: 319ms	remaining: 1.72s
156:	learn: 76.1532411	total: 321ms	remaining: 1.72s
157:	learn: 75.9512598	total: 323ms	remaining: 1.72s
158:	learn: 75.6982498	total: 324ms	remaining: 1.71s
159:	learn: 75.5269960	total: 326ms	remaining: 1.71s
160:	learn: 75.3403407	total: 328ms	remaining: 1.71s
161:	learn: 75.1139044	total: 330ms	remaining: 1.7s
162:	learn: 74.9327078	total: 332ms	remaining: 1.7s
163:	learn: 74.5225238	total: 334ms	remaining: 1.7s
164:	learn: 74.3916500	total: 335ms	remaining: 1.7s
165:	learn: 73.9333653	total: 337ms	remaining: 1.69s
166:	learn: 73.5683259	total: 340ms	remaining: 1.7s
167:	learn: 73.3719171	total: 342ms	remaining: 1.69s
168:	learn: 73.1464277	total: 344ms	remaining: 1.69s
169:	learn: 72.9040033	total: 346ms	remaining: 1.69s
170:	learn: 72.7218660	total: 347ms	remaining: 1.68s
171:	learn: 72.5036930	total: 349ms	remaining: 1.68s
172:	learn: 72.3234718	total: 351ms	remaining: 1.68s
173:	learn: 72.2338323	total: 353ms	remaining: 1.67s
174:	learn: 72.0398154	total: 355ms	remaining: 1.67s
175:	learn: 71.9291248	total: 356ms	remaining: 1.67s
176:	learn: 71.8452379	total: 358ms	remaining: 1.66s
177:	learn: 71.7009112	total: 360ms	remaining: 1.66s
178:	learn: 71.3315029	total: 362ms	remaining: 1.66s
179:	learn: 71.2340745	total: 363ms	remaining: 1.65s
180:	learn: 70.8245867	total: 365ms	remaining: 1.65s
181:	learn: 70.6467776	total: 367ms	remaining: 1.65s
182:	learn: 70.3589121	total: 369ms	remaining: 1.65s
183:	learn: 70.2240639	total: 371ms	remaining: 1.65s
184:	learn: 69.9304880	total: 372ms	remaining: 1.64s
185:	learn: 69.8368241	total: 375ms	remaining: 1.64s
186:	learn: 69.7457437	total: 377ms	remaining: 1.64s
187:	learn: 69.6528502	total: 379ms	remaining: 1.64s
188:	learn: 69.4295292	total: 381ms	remaining: 1.64s
189:	learn: 69.3504161	total: 383ms	remaining: 1.63s
190:	learn: 69.1285635	total: 385ms	remaining: 1.63s
191:	learn: 68.9587091	total: 387ms	remaining: 1.63s
192:	learn: 68.6330412	total: 388ms	remaining: 1.62s
193:	learn: 68.5062222	total: 391ms	remaining: 1.62s
194:	learn: 68.3960349	total: 393ms	remaining: 1.62s
195:	learn: 68.1813730	total: 396ms	remaining: 1.62s
196:	learn: 68.0754361	total: 397ms	remaining: 1.62s
197:	learn: 67.8014394	total: 398ms	remaining: 1.61s
198:	learn: 67.7039861	total: 401ms	remaining: 1.61s
199:	learn: 67.6009635	total: 403ms	remaining: 1.61s
200:	learn: 67.5029512	total: 404ms	remaining: 1.61s
201:	learn: 67.4158030	total: 406ms	remaining: 1.6s
202:	learn: 67.2744640	total: 408ms	remaining: 1.6s
203:	learn: 66.9578471	total: 410ms	remaining: 1.6s
204:	learn: 66.8560995	total: 412ms	remaining: 1.6s
205:	learn: 66.6528439	total: 414ms	remaining: 1.59s
206:	learn: 66.4103449	total: 416ms	remaining: 1.59s
207:	learn: 66.3334716	total: 417ms	remaining: 1.59s
208:	learn: 65.9577523	total: 419ms	remaining: 1.59s
209:	learn: 65.8009527	total: 422ms	remaining: 1.59s
210:	learn: 65.6943236	total: 426ms	remaining: 1.59s
211:	learn: 65.4589657	total: 427ms	remaining: 1.59s
212:	learn: 65.1184773	total: 429ms	remaining: 1.58s
213:	learn: 64.9638352	total: 431ms	remaining: 1.58s
214:	learn: 64.8722904	total: 433ms	remaining: 1.58s
215:	learn: 64.7628348	total: 434ms	remaining: 1.58s
216:	learn: 64.7161524	total: 436ms	remaining: 1.57s
217:	learn: 64.6316542	total: 438ms	remaining: 1.57s
218:	learn: 64.4303809	total: 440ms	remaining: 1.57s
219:	learn: 64.3448407	total: 441ms	remaining: 1.56s
220:	learn: 64.2714925	total: 443ms	remaining: 1.56s
221:	learn: 64.1654281	total: 445ms	remaining: 1.56s
222:	learn: 63.9661890	total: 448ms	remaining: 1.56s
223:	learn: 63.9412086	total: 450ms	remaining: 1.56s
224:	learn: 63.8991028	total: 453ms	remaining: 1.56s
225:	learn: 63.7720819	total: 455ms	remaining: 1.56s
226:	learn: 63.6730863	total: 457ms	remaining: 1.56s
227:	learn: 63.4671021	total: 459ms	remaining: 1.55s
228:	learn: 63.3460184	total: 461ms	remaining: 1.55s
229:	learn: 63.1897823	total: 463ms	remaining: 1.55s
230:	learn: 62.8882336	total: 465ms	remaining: 1.55s
231:	learn: 62.8616108	total: 467ms	remaining: 1.54s
232:	learn: 62.8461718	total: 468ms	remaining: 1.54s
233:	learn: 62.8272718	total: 470ms	remaining: 1.54s
234:	learn: 62.6905663	total: 472ms	remaining: 1.53s
235:	learn: 62.6424892	total: 473ms	remaining: 1.53s
236:	learn: 62.5179009	total: 475ms	remaining: 1.53s
237:	learn: 62.2328116	total: 477ms	remaining: 1.53s
238:	learn: 62.1854332	total: 478ms	remaining: 1.52s
239:	learn: 62.1702385	total: 480ms	remaining: 1.52s
240:	learn: 62.1322578	total: 483ms	remaining: 1.52s
241:	learn: 62.0025445	total: 484ms	remaining: 1.52s
242:	learn: 61.9868550	total: 486ms	remaining: 1.51s
243:	learn: 61.9787045	total: 488ms	remaining: 1.51s
244:	learn: 61.9702176	total: 489ms	remaining: 1.51s
245:	learn: 61.9358848	total: 491ms	remaining: 1.5s
246:	learn: 61.9206059	total: 492ms	remaining: 1.5s
247:	learn: 61.8630591	total: 494ms	remaining: 1.5s
248:	learn: 61.7328059	total: 496ms	remaining: 1.5s
249:	learn: 61.6843382	total: 498ms	remaining: 1.49s
250:	learn: 61.5457300	total: 500ms	remaining: 1.49s
251:	learn: 61.5054753	total: 501ms	remaining: 1.49s
252:	learn: 61.4045559	total: 504ms	remaining: 1.49s
253:	learn: 61.3956114	total: 506ms	remaining: 1.49s
254:	learn: 61.3245916	total: 508ms	remaining: 1.48s
255:	learn: 61.2084488	total: 510ms	remaining: 1.48s
256:	learn: 61.1883973	total: 512ms	remaining: 1.48s
257:	learn: 61.0841655	total: 514ms	remaining: 1.48s
258:	learn: 61.0758387	total: 516ms	remaining: 1.48s
259:	learn: 61.0539032	total: 518ms	remaining: 1.48s
260:	learn: 60.9371092	total: 520ms	remaining: 1.47s
261:	learn: 60.7091398	total: 523ms	remaining: 1.47s
262:	learn: 60.5424927	total: 524ms	remaining: 1.47s
263:	learn: 60.5330131	total: 527ms	remaining: 1.47s
264:	learn: 60.4318672	total: 529ms	remaining: 1.47s
265:	learn: 60.3191478	total: 532ms	remaining: 1.47s
266:	learn: 60.1094550	total: 537ms	remaining: 1.47s
267:	learn: 60.0441199	total: 539ms	remaining: 1.47s
268:	learn: 59.8956050	total: 540ms	remaining: 1.47s
269:	learn: 59.7882421	total: 542ms	remaining: 1.47s
270:	learn: 59.7015745	total: 544ms	remaining: 1.46s
271:	learn: 59.6849868	total: 546ms	remaining: 1.46s
272:	learn: 59.5313663	total: 548ms	remaining: 1.46s
273:	learn: 59.3469473	total: 550ms	remaining: 1.46s
274:	learn: 59.3383266	total: 552ms	remaining: 1.45s
275:	learn: 59.1809373	total: 553ms	remaining: 1.45s
276:	learn: 59.0981544	total: 555ms	remaining: 1.45s
277:	learn: 58.9944765	total: 558ms	remaining: 1.45s
278:	learn: 58.9019730	total: 561ms	remaining: 1.45s
279:	learn: 58.8938844	total: 563ms	remaining: 1.45s
280:	learn: 58.6987376	total: 565ms	remaining: 1.45s
281:	learn: 58.5389618	total: 567ms	remaining: 1.44s
282:	learn: 58.3973185	total: 570ms	remaining: 1.44s
283:	learn: 58.2553013	total: 572ms	remaining: 1.44s
284:	learn: 58.1142177	total: 575ms	remaining: 1.44s
285:	learn: 58.0596795	total: 577ms	remaining: 1.44s
286:	learn: 57.8106334	total: 579ms	remaining: 1.44s
287:	learn: 57.7277784	total: 583ms	remaining: 1.44s
288:	learn: 57.5740969	total: 585ms	remaining: 1.44s
289:	learn: 57.3889822	total: 586ms	remaining: 1.43s
290:	learn: 57.2941040	total: 588ms	remaining: 1.43s
291:	learn: 57.0917641	total: 590ms	remaining: 1.43s
292:	learn: 56.9967984	total: 593ms	remaining: 1.43s
293:	learn: 56.8762124	total: 595ms	remaining: 1.43s
294:	learn: 56.7414147	total: 597ms	remaining: 1.43s
295:	learn: 56.5683088	total: 599ms	remaining: 1.42s
296:	learn: 56.4599785	total: 601ms	remaining: 1.42s
297:	learn: 56.3434530	total: 603ms	remaining: 1.42s
298:	learn: 56.2377358	total: 604ms	remaining: 1.42s
299:	learn: 56.1499624	total: 607ms	remaining: 1.42s
300:	learn: 56.0696512	total: 608ms	remaining: 1.41s
301:	learn: 55.9315184	total: 610ms	remaining: 1.41s
302:	learn: 55.7959074	total: 612ms	remaining: 1.41s
303:	learn: 55.6601277	total: 614ms	remaining: 1.41s
304:	learn: 55.5616025	total: 616ms	remaining: 1.4s
305:	learn: 55.4980744	total: 618ms	remaining: 1.4s
306:	learn: 55.3623793	total: 620ms	remaining: 1.4s
307:	learn: 55.2649405	total: 623ms	remaining: 1.4s
308:	learn: 55.1809024	total: 625ms	remaining: 1.4s
309:	learn: 55.1016662	total: 626ms	remaining: 1.39s
310:	learn: 55.0295233	total: 629ms	remaining: 1.39s
311:	learn: 55.0081222	total: 631ms	remaining: 1.39s
312:	learn: 54.9723400	total: 633ms	remaining: 1.39s
313:	learn: 54.8766621	total: 634ms	remaining: 1.39s
314:	learn: 54.6915832	total: 636ms	remaining: 1.38s
315:	learn: 54.6080102	total: 638ms	remaining: 1.38s
316:	learn: 54.4697287	total: 640ms	remaining: 1.38s
317:	learn: 54.2981809	total: 642ms	remaining: 1.38s
318:	learn: 54.1048816	total: 644ms	remaining: 1.38s
319:	learn: 53.9540265	total: 646ms	remaining: 1.37s
320:	learn: 53.8584243	total: 648ms	remaining: 1.37s
321:	learn: 53.7356437	total: 650ms	remaining: 1.37s
322:	learn: 53.6151469	total: 652ms	remaining: 1.37s
323:	learn: 53.5510392	total: 654ms	remaining: 1.36s
324:	learn: 53.4986902	total: 657ms	remaining: 1.36s
325:	learn: 53.4802492	total: 659ms	remaining: 1.36s
326:	learn: 53.3765087	total: 663ms	remaining: 1.36s
327:	learn: 53.3612136	total: 665ms	remaining: 1.36s
328:	learn: 53.2107725	total: 666ms	remaining: 1.36s
329:	learn: 53.1703151	total: 668ms	remaining: 1.35s
330:	learn: 53.0578511	total: 670ms	remaining: 1.35s
331:	learn: 52.9505552	total: 672ms	remaining: 1.35s
332:	learn: 52.8782930	total: 673ms	remaining: 1.35s
333:	learn: 52.8276521	total: 675ms	remaining: 1.34s
334:	learn: 52.7059071	total: 677ms	remaining: 1.34s
335:	learn: 52.5601087	total: 679ms	remaining: 1.34s
336:	learn: 52.3751515	total: 680ms	remaining: 1.34s
337:	learn: 52.2278615	total: 682ms	remaining: 1.33s
338:	learn: 52.1271192	total: 684ms	remaining: 1.33s
339:	learn: 52.0378198	total: 686ms	remaining: 1.33s
340:	learn: 51.8888395	total: 688ms	remaining: 1.33s
341:	learn: 51.7285023	total: 690ms	remaining: 1.33s
342:	learn: 51.6370028	total: 691ms	remaining: 1.32s
343:	learn: 51.5277343	total: 693ms	remaining: 1.32s
344:	learn: 51.4124935	total: 696ms	remaining: 1.32s
345:	learn: 51.2992996	total: 698ms	remaining: 1.32s
346:	learn: 51.2420295	total: 700ms	remaining: 1.32s
347:	learn: 51.1662693	total: 701ms	remaining: 1.31s
348:	learn: 51.0749263	total: 703ms	remaining: 1.31s
349:	learn: 50.9690078	total: 705ms	remaining: 1.31s
350:	learn: 50.8990159	total: 707ms	remaining: 1.31s
351:	learn: 50.7954681	total: 710ms	remaining: 1.31s
352:	learn: 50.6853251	total: 712ms	remaining: 1.3s
353:	learn: 50.6617197	total: 713ms	remaining: 1.3s
354:	learn: 50.5385420	total: 715ms	remaining: 1.3s
355:	learn: 50.4614057	total: 718ms	remaining: 1.3s
356:	learn: 50.4120226	total: 720ms	remaining: 1.3s
357:	learn: 50.3416386	total: 721ms	remaining: 1.29s
358:	learn: 50.2944597	total: 724ms	remaining: 1.29s
359:	learn: 50.2067033	total: 726ms	remaining: 1.29s
360:	learn: 50.1025145	total: 728ms	remaining: 1.29s
361:	learn: 50.0798239	total: 730ms	remaining: 1.28s
362:	learn: 50.0705779	total: 731ms	remaining: 1.28s
363:	learn: 49.9147015	total: 733ms	remaining: 1.28s
364:	learn: 49.8840818	total: 736ms	remaining: 1.28s
365:	learn: 49.8545168	total: 737ms	remaining: 1.28s
366:	learn: 49.8152592	total: 739ms	remaining: 1.27s
367:	learn: 49.7990880	total: 741ms	remaining: 1.27s
368:	learn: 49.7803952	total: 743ms	remaining: 1.27s
369:	learn: 49.6563021	total: 745ms	remaining: 1.27s
370:	learn: 49.5598110	total: 747ms	remaining: 1.26s
371:	learn: 49.5340316	total: 749ms	remaining: 1.26s
372:	learn: 49.4819924	total: 751ms	remaining: 1.26s
373:	learn: 49.4097253	total: 753ms	remaining: 1.26s
374:	learn: 49.3266979	total: 755ms	remaining: 1.26s
375:	learn: 49.2150754	total: 757ms	remaining: 1.26s

/Users/nals_macbook_108/Library/Python/3.9/lib/python/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

In [116]:
pd.DataFrame(results).sort_values(by=['r2', 'mse'],
                                  ascending=[False, True]).reset_index(drop=True)

,model,r2,mse,rmse,mae,model_train
0,catboost,0.999190,8.840423e+03,94.023524,32.801286,(CatBoostRegressor(loss_function='RMSE'))
1,lightGBM,0.999052,1.034396e+04,101.705257,16.942697,(LGBMRegressor())
2,xgboost,0.999034,1.054266e+04,102.677439,26.606473,"(XGBRegressor(base_score=None, booster=None, c..."
3,histogram,0.996580,3.731897e+04,193.181177,34.980749,(HistGradientBoostingRegressor())
4,SVR_linear,0.510094,5.345506e+06,2312.035097,1077.167490,(SVR(kernel='linear'))
5,SVR_rbf,-0.078482,1.176763e+07,3430.397493,2075.170253,(SVR())
6,SVR_poly,-0.078566,1.176855e+07,3430.531587,2075.283187,(SVR(kernel='poly'))
7,linear,-1.830267,3.088186e+07,5557.145221,1270.198116,(LinearRegression())

### Metric đánh giá 
Metric r2: tỉ lệ phương sai dữ liệu mà mô hình giải thchs được
- r2 = 1.0 --> hoàn hảo, r2 = 0 --> không tốt hơn dự đoán trung bình, r2 < 0 --> tệ hơn dự đoán trung bình
Metric rmse/mse: sai số bình phương - phạt năng các lỗi lớn
Metric mae: sai số tuyệt đối trung bình - ít bị ảnh hưởng bởi outlier
### Phân tích chi tiết
- Nhóm gradient boosting (Mô hình catboost, lightGBM, XGboost, histogram)) hoạt động tốt với r2 = 0.999, nghĩa là mô hình giải thích được > 99,9% biến động của dữ liệu, phù hợp với dữ liệu cấu trúc phi tuyến
- SVR Linear có r2 = 0.51 chỉ giải thích được ~ 51% biến động của dữ liệu, cho thấy dữ liệu tính phi tuyến mạnh, kernel tuyến tính không đủ phức tạp
- SVR_rbf, SVR_poly và Linear Regression có r2 <0 - tệ, nguyên nhân:
+ dữ liệu chưa được chuẩn hoá (scaling) - SVR và Linear Regression rất nhạy cảm với scale features
+ dữ liệu có thể có ôutpier lớn ảnh hưởng nặng

--> Phân tích tiếpnhóm Gradient Boosting, tốt nhất sử dụng model Catboost làm mô hình chính vì r2 cao nhất và mae thấp nhất (32.8).